server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/account_service_dev
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

